import type { LanguageCode } from "./i18n";

export type IngredientMeta = {
  id: string;
  name_zh: string;
  name_en: string;
  name_id: string;
  name_hi: string;
  originCountry: string;
  originStory_zh: string;
  originStory_en: string;
  originStory_id: string;
  originStory_hi: string;
  funFact_zh: string;
  funFact_en: string;
  funFact_id: string;
  funFact_hi: string;
};

export const INGREDIENTS: Record<string, IngredientMeta> = {
  Apple: {
    id: "apple",
    name_zh: "苹果",
    name_en: "Apple",
    name_id: "Apel",
    name_hi: "सेब",
    originCountry: "Kazakhstan 🇰🇿",
    originStory_zh: "现代栽培苹果被认为起源于中亚地区。随着贸易与迁徙，苹果逐渐传播到欧洲与世界各地。",
    originStory_en: "Modern cultivated apples are thought to originate in Central Asia. Through trade and migration, they spread to Europe and around the world.",
    originStory_id: "Apel budidaya modern diyakini berasal dari Asia Tengah. Lewat perdagangan dan perpindahan manusia, apel menyebar ke Eropa dan seluruh dunia.",
    originStory_hi: "आधुनिक सेब की उत्पत्ति मध्य एशिया में मानी जाती है। व्यापार और प्रवास के साथ यह यूरोप और दुनिया भर में फैल गया।",
    funFact_zh: "苹果切开后变褐色，是因为酶和空气接触发生氧化反应。",
    funFact_en: "Apples turn brown after cutting because enzymes react with oxygen.",
    funFact_id: "Apel menjadi kecokelatan setelah dipotong karena enzim bereaksi dengan oksigen.",
    funFact_hi: "कटने के बाद सेब का भूरा होना ऑक्सीजन के साथ एंज़ाइम प्रतिक्रिया के कारण होता है।"
  },
  Bacon: {
    id: "bacon",
    name_zh: "培根",
    name_en: "Bacon",
    name_id: "Bacon",
    name_hi: "बेकन",
    originCountry: "Europe 🇪🇺",
    originStory_zh: "腌制与熏制猪肉在欧洲历史悠久，用来延长保存时间。不同地区发展出了各自的盐渍与烟熏风格。",
    originStory_en: "Curing and smoking pork has long roots in Europe as a way to preserve meat. Regions developed distinct salting and smoking styles.",
    originStory_id: "Mengawetkan daging babi dengan garam dan asap punya sejarah panjang di Eropa. Tiap daerah berkembang dengan gaya penggaraman dan pengasapan sendiri.",
    originStory_hi: "यूरोप में मांस को लंबे समय तक सुरक्षित रखने के लिए नमक और धुएँ से संरक्षित करने की परंपरा रही है। अलग क्षेत्रों के अपने-अपने तरीके बने।",
    funFact_zh: "培根的香味很多来自烟熏与“美拉德反应”的焦香。",
    funFact_en: "Bacon’s aroma comes from smoking and Maillard browning during cooking.",
    funFact_id: "Aroma bacon berasal dari pengasapan dan reaksi Maillard saat dimasak.",
    funFact_hi: "बेकन की खुशबू धुएँ और पकाने के दौरान होने वाली मैयार्ड ब्राउनिंग से आती है।"
  },
  "Basmati rice": {
    id: "basmati_rice",
    name_zh: "巴斯马蒂米",
    name_en: "Basmati rice",
    name_id: "Beras basmati",
    name_hi: "बासमती चावल",
    originCountry: "India & Pakistan 🇮🇳🇵🇰",
    originStory_zh: "巴斯马蒂以细长米粒和香气著称，传统上在南亚地区种植。它常用于抓饭等需要颗粒分明的米饭料理。",
    originStory_en: "Basmati is known for long grains and fragrance, traditionally grown in South Asia. It’s prized for dishes where grains stay separate.",
    originStory_id: "Basmati terkenal dengan bulir panjang dan aromanya, ditanam secara tradisional di Asia Selatan. Cocok untuk hidangan yang butir nasinya terpisah.",
    originStory_hi: "बासमती अपनी लंबी दानों और खुशबू के लिए प्रसिद्ध है, और परंपरागत रूप से दक्षिण एशिया में उगाई जाती है। इसे ऐसे व्यंजनों में पसंद किया जाता है जहाँ दाने अलग रहें।",
    funFact_zh: "冲洗米能洗掉表面淀粉，让煮出的米饭更松散。",
    funFact_en: "Rinsing rice removes surface starch, helping grains cook up fluffier.",
    funFact_id: "Mencuci beras mengurangi pati permukaan sehingga hasilnya lebih pulen-terpisah.",
    funFact_hi: "चावल धोने से सतही स्टार्च कम होता है, जिससे दाने अधिक फूले-फूले और अलग बनते हैं।"
  },
  "Bean sprout": {
    id: "bean_sprout",
    name_zh: "豆芽",
    name_en: "Bean sprout",
    name_id: "Tauge",
    name_hi: "अंकुरित मूंग",
    originCountry: "East Asia 🇨🇳",
    originStory_zh: "豆芽是在温暖潮湿条件下让豆类发芽获得的嫩芽。它清脆爽口，常用于快炒、凉拌或汤面配菜。",
    originStory_en: "Bean sprouts are young shoots grown by sprouting beans in warm, moist conditions. They’re crisp and often used in quick stir-fries and soups.",
    originStory_id: "Tauge adalah tunas muda dari kacang yang dikecambahkan. Teksturnya renyah dan sering dipakai untuk tumisan cepat atau sup.",
    originStory_hi: "अंकुरित दाल/बीन्स गर्म और नम वातावरण में उगाए गए कोमल अंकुर होते हैं। ये कुरकुरे होते हैं और जल्दी स्टिर-फ्राय या सूप में उपयोग होते हैं।",
    funFact_zh: "豆芽怕久炒——下锅后大火快炒更能保持爽脆。",
    funFact_en: "Sprouts are best cooked fast on high heat to keep them crunchy.",
    funFact_id: "Tauge paling enak dimasak cepat dengan api besar agar tetap renyah.",
    funFact_hi: "अंकुर को तेज़ आँच पर जल्दी पकाने से कुरकुरापन बना रहता है।"
  },
  Beef: {
    id: "beef",
    name_zh: "牛肉",
    name_en: "Beef",
    name_id: "Daging sapi",
    name_hi: "गोमांस",
    originCountry: "Worldwide 🌍",
    originStory_zh: "牛肉作为重要蛋白来源在世界多地都有悠久饮食传统。不同地区因饲养方式与烹饪习惯而形成多样风味。",
    originStory_en: "Beef has long been an important protein in many cuisines worldwide. Farming practices and cooking traditions create varied flavors.",
    originStory_id: "Daging sapi menjadi sumber protein penting di banyak masakan dunia. Cara beternak dan teknik memasak membuat rasanya beragam.",
    originStory_hi: "दुनिया भर की कई रसोइयों में गोमांस लंबे समय से एक महत्वपूर्ण प्रोटीन रहा है। पालन-पोषण और पकाने की परंपराएँ स्वाद में विविधता लाती हैं।",
    funFact_zh: "逆纹切牛肉能缩短肌纤维，口感更嫩。",
    funFact_en: "Slicing beef against the grain shortens muscle fibers and makes bites feel more tender.",
    funFact_id: "Memotong melawan serat membuat daging terasa lebih empuk.",
    funFact_hi: "रेशों के विपरीत काटने से फाइबर छोटे होते हैं और मांस अधिक नरम लगता है।"
  },
  Bun: {
    id: "bun",
    name_zh: "面包胚",
    name_en: "Bun",
    name_id: "Roti bun",
    name_hi: "बन",
    originCountry: "Europe 🇪🇺",
    originStory_zh: "小圆面包在欧洲烘焙传统中很常见，后来在各地衍生出不同配方与口感。它也成为汉堡等夹馅食品的经典载体。",
    originStory_en: "Small bread rolls are common in European baking traditions and evolved into many local styles. They became a classic carrier for sandwiches and burgers.",
    originStory_id: "Roti bulat kecil umum dalam tradisi roti Eropa dan berkembang jadi banyak gaya. Kini jadi ‘wadah’ klasik untuk sandwich dan burger.",
    originStory_hi: "यूरोपीय बेकिंग परंपराओं में छोटे ब्रेड रोल आम हैं और समय के साथ कई स्थानीय शैलियाँ बनीं। ये सैंडविच/बर्गर के लिए क्लासिक आधार बन गए।",
    funFact_zh: "轻微烘烤面包能让表面更香、更不易被酱汁浸软。",
    funFact_en: "Toasting a bun adds aroma and helps it resist getting soggy from sauces.",
    funFact_id: "Memanggang roti sebentar menambah aroma dan membuatnya tidak cepat lembek oleh saus.",
    funFact_hi: "बन को हल्का टोस्ट करने से खुशबू बढ़ती है और सॉस से जल्दी नरम नहीं पड़ता।"
  },
  Butter: {
    id: "butter",
    name_zh: "黄油",
    name_en: "Butter",
    name_id: "Mentega",
    name_hi: "मक्खन",
    originCountry: "Worldwide 🌍",
    originStory_zh: "黄油是把奶油搅打分离出的乳脂，许多地区都把它作为烹饪与烘焙的重要脂肪来源。",
    originStory_en: "Butter is made by churning cream into fat and buttermilk, and it’s a key cooking and baking fat in many cuisines.",
    originStory_id: "Mentega dibuat dengan mengocok krim hingga terpisah menjadi lemak dan buttermilk, dan menjadi lemak penting untuk masak/baking.",
    originStory_hi: "मक्खन क्रीम को मथकर बनाया जाता है, और कई रसोइयों में यह पकाने व बेकिंग का अहम फैट है।",
    funFact_zh: "黄油加热到起泡并散发坚果香时，通常意味着水分在蒸发、乳固形物在上色。",
    funFact_en: "When butter foams and smells nutty, water is evaporating and milk solids are browning.",
    funFact_id: "Saat mentega berbusa dan beraroma ‘kacang’, air menguap dan padatan susu mulai kecokelatan.",
    funFact_hi: "जब मक्खन झाग बनाता है और नटी खुशबू आती है, तो पानी उड़ रहा होता है और मिल्क सॉलिड्स ब्राउन हो रहे होते हैं।"
  },
  "Cheddar cheese": {
    id: "cheddar_cheese",
    name_zh: "切达奶酪",
    name_en: "Cheddar cheese",
    name_id: "Keju cheddar",
    name_hi: "चेडर चीज़",
    originCountry: "England 🇬🇧",
    originStory_zh: "切达起源于英格兰切达村一带，后来成为世界最常见的硬质奶酪之一。熟成时间会影响风味强度。",
    originStory_en: "Cheddar originated in England near the village of Cheddar and became one of the world’s most popular hard cheeses. Aging changes its sharpness.",
    originStory_id: "Cheddar berasal dari Inggris dekat desa Cheddar dan menjadi salah satu keju keras paling populer di dunia. Lama pematangan memengaruhi ketajaman rasa.",
    originStory_hi: "चेडर की शुरुआत इंग्लैंड के चेडर क्षेत्र से मानी जाती है और यह दुनिया के सबसे लोकप्रिय हार्ड चीज़ में से एक है। उम्र बढ़ने के साथ इसका स्वाद तीखा होता जाता है।",
    funFact_zh: "奶酪融化的“拉丝感”与蛋白质网络和含水量有关。",
    funFact_en: "Stretchy melt depends on the protein network and moisture content.",
    funFact_id: "Efek ‘melelah’ dan mulur dipengaruhi jaringan protein dan kadar air.",
    funFact_hi: "चीज़ का स्ट्रेची मेल्ट उसके प्रोटीन नेटवर्क और नमी पर निर्भर करता है।"
  },
  Chicken: {
    id: "chicken",
    name_zh: "鸡肉",
    name_en: "Chicken",
    name_id: "Ayam",
    name_hi: "चिकन",
    originCountry: "Southeast Asia 🇸🇬",
    originStory_zh: "家鸡的驯化历史悠久，随后传播到世界各地，成为最普遍的肉类之一。不同烹饪方式能呈现截然不同的口感。",
    originStory_en: "Domesticated chickens have a long history and spread globally, becoming one of the most common meats. Cooking methods create very different textures.",
    originStory_id: "Ayam peliharaan punya sejarah panjang dan menyebar ke seluruh dunia. Cara memasak membuat teksturnya bisa sangat berbeda.",
    originStory_hi: "पालतू मुर्गे का इतिहास पुराना है और यह दुनिया भर में फैल गया, जिससे यह सबसे आम मांसों में शामिल हो गया। पकाने के तरीके से टेक्सचर बदल जाता है।",
    funFact_zh: "鸡腿肉比鸡胸更不易柴，因为脂肪含量更高。",
    funFact_en: "Chicken thighs stay juicier than breast because they contain more fat.",
    funFact_id: "Paha ayam lebih juicy daripada dada karena lemaknya lebih banyak.",
    funFact_hi: "चिकन थाई ब्रेस्ट की तुलना में ज्यादा जूसी रहता है क्योंकि उसमें फैट अधिक होता है।"
  },
  Chili: {
    id: "chili",
    name_zh: "辣椒",
    name_en: "Chili",
    name_id: "Cabai",
    name_hi: "मिर्च",
    originCountry: "Mexico 🇲🇽",
    originStory_zh: "辣椒原产于美洲，后来通过交流传播到亚洲与欧洲，深刻改变了许多地区的饮食。",
    originStory_en: "Chilies originated in the Americas and later spread to Asia and Europe, reshaping cuisines across the world.",
    originStory_id: "Cabai berasal dari benua Amerika lalu menyebar ke Asia dan Eropa, mengubah banyak masakan dunia.",
    originStory_hi: "मिर्च की उत्पत्ति अमेरिका महाद्वीप में हुई और बाद में यह एशिया व यूरोप पहुँची, जिससे कई रसोइयों का स्वाद बदल गया।",
    funFact_zh: "辣椒的“辣”来自辣椒素，它对温度不敏感，但能刺激痛觉受体。",
    funFact_en: "Chili heat comes from capsaicin, which triggers pain receptors rather than temperature sensors.",
    funFact_id: "Rasa pedas berasal dari capsaicin yang memicu reseptor nyeri, bukan sensor suhu.",
    funFact_hi: "मिर्च की तीखापन कैप्सेसिन से आता है, जो तापमान नहीं बल्कि दर्द के रिसेप्टर्स को सक्रिय करता है।"
  },
  "Chili powder": {
    id: "chili_powder",
    name_zh: "辣椒粉",
    name_en: "Chili powder",
    name_id: "Bubuk cabai",
    name_hi: "मिर्च पाउडर",
    originCountry: "Americas 🇲🇽",
    originStory_zh: "把干辣椒研磨成粉能更方便保存和使用。不同辣椒品种与烘干方式会带来不同香气。",
    originStory_en: "Grinding dried chilies into powder makes them easy to store and use. Varieties and drying methods change the aroma.",
    originStory_id: "Menggiling cabai kering jadi bubuk memudahkan penyimpanan dan penggunaan. Varietas dan cara pengeringan memengaruhi aromanya.",
    originStory_hi: "सूखी मिर्च को पीसकर पाउडर बनाना स्टोर और उपयोग में आसान बनाता है। किस्म और सुखाने का तरीका खुशबू बदल देता है।",
    funFact_zh: "辣椒粉放久会变淡，是挥发性香气逐渐流失。",
    funFact_en: "Chili powder fades over time as aromatic compounds dissipate.",
    funFact_id: "Bubuk cabai bisa melemah aromanya seiring waktu karena senyawa aromatik menguap.",
    funFact_hi: "समय के साथ मिर्च पाउडर की खुशबू कम हो सकती है क्योंकि सुगंधित यौगिक उड़ जाते हैं।"
  },
  "Cold water": {
    id: "cold_water",
    name_zh: "冷水",
    name_en: "Cold water",
    name_id: "Air dingin",
    name_hi: "ठंडा पानी",
    originCountry: "Everywhere 🌍",
    originStory_zh: "冷水常用于和面、调酱或控制温度，帮助掌握质地。厨房里的“温度”往往和味道一样重要。",
    originStory_en: "Cold water is used in doughs, sauces, and temperature control to manage texture. In cooking, temperature can matter as much as flavor.",
    originStory_id: "Air dingin dipakai untuk adonan, saus, dan mengatur suhu agar tekstur terkontrol. Suhu sering sama pentingnya dengan rasa.",
    originStory_hi: "ठंडा पानी आटा, सॉस और तापमान नियंत्रण में टेक्सचर संभालने के लिए उपयोग होता है। पकाने में तापमान स्वाद जितना ही अहम हो सकता है।",
    funFact_zh: "冷水能减缓面筋形成，某些面点会因此更酥。",
    funFact_en: "Cold water can slow gluten development, affecting tenderness in some doughs.",
    funFact_id: "Air dingin bisa memperlambat pembentukan gluten dan memengaruhi kelembutan adonan tertentu.",
    funFact_hi: "ठंडा पानी ग्लूटेन बनने की गति धीमी कर सकता है, जिससे कुछ आटे अधिक कोमल बनते हैं।"
  },
  "Coconut milk": {
    id: "coconut_milk",
    name_zh: "椰浆",
    name_en: "Coconut milk",
    name_id: "Santan",
    name_hi: "नारियल दूध",
    originCountry: "Southeast Asia 🌴",
    originStory_zh: "椰浆来自椰肉加水研磨挤压，是东南亚与南亚菜系的常见底味。它能让香料更圆润、汤汁更浓。",
    originStory_en: "Coconut milk comes from grated coconut flesh pressed with water and is common in Southeast and South Asian cooking. It softens spice and enriches sauces.",
    originStory_id: "Santan dibuat dari kelapa parut yang diperas dengan air dan umum di masakan Asia Tenggara/ Selatan. Santan membuat bumbu lebih ‘bulat’ dan kuah lebih kaya.",
    originStory_hi: "नारियल दूध कद्दूकस नारियल को पानी के साथ दबाकर निकाला जाता है और यह दक्षिण-पूर्व व दक्षिण एशियाई पकवानों में आम है। यह मसालों को राउंड करता है और सॉस को रिच बनाता है।",
    funFact_zh: "椰浆加热后油水会分离，这是正常现象，搅匀即可。",
    funFact_en: "Coconut milk can separate when heated — it’s normal and can be stirred back together.",
    funFact_id: "Santan bisa pecah saat dipanaskan — itu normal dan bisa diaduk kembali.",
    funFact_hi: "नारियल दूध गर्म होने पर अलग हो सकता है — यह सामान्य है और इसे फिर से मिला सकते हैं।"
  },
  "Cooked rice (day-old)": {
    id: "day_old_rice",
    name_zh: "隔夜米饭",
    name_en: "Cooked rice (day-old)",
    name_id: "Nasi semalam",
    name_hi: "रात का चावल",
    originCountry: "Everywhere 🌍",
    originStory_zh: "隔夜饭水分更少、更松散，特别适合做炒饭。很多家庭用它把剩饭变成新的一餐。",
    originStory_en: "Day-old rice is drier and more separated, which makes it ideal for fried rice. It’s a classic way to transform leftovers into a new meal.",
    originStory_id: "Nasi semalam lebih kering dan butirannya terpisah, cocok untuk nasi goreng. Ini cara klasik mengolah sisa nasi jadi hidangan baru.",
    originStory_hi: "रात का बचा चावल सूखा और दानेदार होता है, इसलिए फ्राइड राइस के लिए बढ़िया है। यह बचे हुए खाने को नए भोजन में बदलने का क्लासिक तरीका है।",
    funFact_zh: "米饭冷却会让淀粉回生，口感更硬一些，但更适合炒。",
    funFact_en: "As rice cools, starch retrogrades, making it firmer — great for stir-frying.",
    funFact_id: "Saat nasi dingin, patinya ‘menguat’ sehingga lebih firm — bagus untuk ditumis.",
    funFact_hi: "चावल ठंडा होने पर स्टार्च सेट हो जाता है और चावल थोड़ा फर्म होता है — स्टिर-फ्राय के लिए अच्छा।"
  },
  "Cooking wine": {
    id: "cooking_wine",
    name_zh: "料酒",
    name_en: "Cooking wine",
    name_id: "Anggur masak",
    name_hi: "कुकिंग वाइन",
    originCountry: "Worldwide 🍷",
    originStory_zh: "烹饪用酒在很多菜系中用于去腥、提香和增加层次。加热会挥发酒精，留下香气成分。",
    originStory_en: "Cooking wine is used in many cuisines to reduce odors and add aroma and depth. Heat evaporates alcohol, leaving flavorful compounds behind.",
    originStory_id: "Wine masak dipakai untuk mengurangi bau dan menambah aroma serta kedalaman rasa. Panas menguapkan alkohol dan meninggalkan senyawa rasa.",
    originStory_hi: "कुकिंग वाइन कई रसोइयों में गंध कम करने और खुशबू/गहराई जोड़ने के लिए उपयोग होती है। गर्म करने पर अल्कोहल उड़ता है और स्वाद के यौगिक रह जाते हैं।",
    funFact_zh: "少量酒加热后能“带出香气”，但过量会让味道发酸或发苦。",
    funFact_en: "A little can boost aroma, but too much may taste sharp or bitter.",
    funFact_id: "Sedikit bisa mengangkat aroma, tapi kebanyakan bisa terasa tajam atau pahit.",
    funFact_hi: "थोड़ा सा खुशबू बढ़ाता है, लेकिन ज्यादा होने पर स्वाद तीखा या कड़वा लग सकता है।"
  },
  "Coriander leaves": {
    id: "coriander_leaves",
    name_zh: "香菜",
    name_en: "Coriander leaves",
    name_id: "Daun ketumbar",
    name_hi: "हरा धनिया",
    originCountry: "Mediterranean 🌿",
    originStory_zh: "香菜在多地都有很长的栽培历史，常在出锅前加入，带来清新的草本香气。",
    originStory_en: "Coriander has a long cultivation history and is often added at the end for fresh herbal aroma.",
    originStory_id: "Ketumbar punya sejarah budidaya panjang dan sering ditambahkan di akhir agar aromanya tetap segar.",
    originStory_hi: "धनिया का उपयोग लंबे समय से होता आया है और इसे अक्सर अंत में डालते हैं ताकि ताज़ी हर्बल खुशबू बनी रहे।",
    funFact_zh: "香菜的香味分子很容易挥发，所以久煮会变淡。",
    funFact_en: "Coriander’s aroma is volatile, so long cooking can dull it.",
    funFact_id: "Aroma ketumbar mudah menguap, jadi memasak terlalu lama bisa mengurangi aromanya.",
    funFact_hi: "धनिया की खुशबू जल्दी उड़ती है, इसलिए ज्यादा देर पकाने से स्वाद फीका हो सकता है।"
  },
  Cucumber: {
    id: "cucumber",
    name_zh: "黄瓜",
    name_en: "Cucumber",
    name_id: "Mentimun",
    name_hi: "खीरा",
    originCountry: "India 🇮🇳",
    originStory_zh: "黄瓜被认为起源于南亚地区，后来传播到世界各地。它清爽多汁，常用于凉拌或配菜。",
    originStory_en: "Cucumbers are thought to have originated in South Asia and spread widely. They’re crisp and hydrating, common in salads and sides.",
    originStory_id: "Mentimun diyakini berasal dari Asia Selatan lalu menyebar luas. Rasanya segar dan berair, sering untuk salad dan lauk.",
    originStory_hi: "खीरे की उत्पत्ति दक्षिण एशिया में मानी जाती है और बाद में यह दुनिया भर में फैल गया। यह कुरकुरा और पानीदार होता है, सलाद/साइड में आम।",
    funFact_zh: "黄瓜主要成分是水，但也含有带来清香的挥发物。",
    funFact_en: "Cucumbers are mostly water, but aromatic compounds give them their fresh smell.",
    funFact_id: "Mentimun sebagian besar air, tapi senyawa aromatik memberi bau segarnya.",
    funFact_hi: "खीरा ज्यादातर पानी होता है, लेकिन कुछ सुगंधित यौगिक इसकी ताज़ी महक देते हैं।"
  },
  "Desiccated coconut": {
    id: "desiccated_coconut",
    name_zh: "椰蓉",
    name_en: "Desiccated coconut",
    name_id: "Kelapa parut kering",
    name_hi: "सूखा नारियल बुरादा",
    originCountry: "Tropics 🌴",
    originStory_zh: "椰蓉是把椰肉脱水后制成的干燥原料，便于保存。它常用于甜点、咖喱和撒料增香。",
    originStory_en: "Desiccated coconut is dried coconut flesh for long storage. It’s used in desserts, curries, and as a fragrant topping.",
    originStory_id: "Kelapa parut kering adalah kelapa yang dikeringkan agar awet. Dipakai untuk kue, kari, atau taburan.",
    originStory_hi: "सूखा नारियल बुरादा नारियल के गूदे को सुखाकर बनाया जाता है ताकि लंबे समय तक रखा जा सके। इसे मिठाइयों, करी और टॉपिंग में इस्तेमाल करते हैं।",
    funFact_zh: "烘烤椰蓉会让香气更像坚果，颜色也会变金黄。",
    funFact_en: "Toasting coconut intensifies nutty aroma and turns it golden.",
    funFact_id: "Menyangrai kelapa membuat aromanya lebih ‘kacang’ dan warnanya keemasan.",
    funFact_hi: "नारियल बुरादे को टोस्ट करने से नटी खुशबू बढ़ती है और रंग सुनहरा हो जाता है।"
  },
  "Dried shrimp": {
    id: "dried_shrimp",
    name_zh: "虾米",
    name_en: "Dried shrimp",
    name_id: "Udang kering",
    name_hi: "सूखी झींगा",
    originCountry: "Coastal Asia 🌊",
    originStory_zh: "晒干的小虾在沿海地区很常见，既方便保存也能带来浓缩鲜味。常用于炒菜、汤或调味。",
    originStory_en: "Dried shrimp are common in coastal regions for preservation and concentrated umami. They add depth to stir-fries and soups.",
    originStory_id: "Udang kering umum di daerah pesisir untuk awet dan memberi umami pekat. Dipakai untuk tumisan dan sup.",
    originStory_hi: "तटीय क्षेत्रों में सूखी झींगा आम है — यह स्टोर करना आसान है और उमामी स्वाद बढ़ाती है। स्टिर-फ्राय और सूप में गहराई देती है।",
    funFact_zh: "少量虾米就能明显提升鲜味，因为含有天然谷氨酸盐。",
    funFact_en: "A small amount can boost savoriness thanks to natural glutamates.",
    funFact_id: "Sedikit saja bisa menguatkan rasa gurih karena mengandung glutamat alami.",
    funFact_hi: "थोड़ी सी भी स्वाद बढ़ा देती है क्योंकि इसमें प्राकृतिक ग्लूटामेट्स होते हैं।"
  },
  Egg: {
    id: "egg",
    name_zh: "鸡蛋",
    name_en: "Egg",
    name_id: "Telur",
    name_hi: "अंडा",
    originCountry: "Worldwide 🌍",
    originStory_zh: "鸡蛋在世界多地都是基础食材，既能做主菜也能做烘焙。加热会让蛋白质凝固，带来不同质地。",
    originStory_en: "Eggs are a foundational ingredient worldwide, used in meals and baking. Heat changes proteins, creating many textures.",
    originStory_id: "Telur adalah bahan dasar di banyak masakan dunia. Panas mengubah protein dan menghasilkan berbagai tekstur.",
    originStory_hi: "अंडे दुनिया भर में आधारभूत सामग्री हैं, भोजन और बेकिंग दोनों में। गर्मी प्रोटीन को बदलती है और कई टेक्सचर बनते हैं।",
    funFact_zh: "蛋黄的颜色受饲料影响很大，颜色深不一定更营养。",
    funFact_en: "Yolk color depends largely on feed and isn’t a direct measure of nutrition.",
    funFact_id: "Warna kuning telur banyak dipengaruhi pakan dan bukan ukuran langsung nilai gizi.",
    funFact_hi: "अंडे की जर्दी का रंग मुख्यतः मुर्गी के आहार पर निर्भर करता है और यह पोषण का सीधा माप नहीं है।"
  },
  "Elbow macaroni": {
    id: "elbow_macaroni",
    name_zh: "通心粉",
    name_en: "Elbow macaroni",
    name_id: "Makaroni siku",
    name_hi: "एल्बो मैकरोनी",
    originCountry: "Italy 🇮🇹",
    originStory_zh: "通心粉是意大利面的一种形状，后来在世界各地成为家常食品。弯曲的形状很适合挂住酱汁。",
    originStory_en: "Elbow macaroni is a pasta shape associated with Italy and became a global staple. Its curve holds sauce well.",
    originStory_id: "Makaroni siku adalah bentuk pasta yang berakar dari Italia dan kini populer di seluruh dunia. Bentuknya membantu saus menempel.",
    originStory_hi: "एल्बो मैकरोनी इटली से जुड़ा पास्ता आकार है और यह दुनिया भर में लोकप्रिय हो गया। इसका घुमाव सॉस को अच्छे से पकड़ता है।",
    funFact_zh: "煮面“回生”后口感会变硬，适合做焗烤或炒面。",
    funFact_en: "Cooked pasta firms up as it cools, which can be useful for baking or pan-frying.",
    funFact_id: "Pasta yang sudah matang akan lebih firm saat dingin, cocok untuk dipanggang atau ditumis.",
    funFact_hi: "पका पास्ता ठंडा होने पर थोड़ा फर्म हो जाता है, जो बेकिंग या पैन-फ्राइ में काम आता है।"
  },
  Garlic: {
    id: "garlic",
    name_zh: "大蒜",
    name_en: "Garlic",
    name_id: "Bawang putih",
    name_hi: "लहसुन",
    originCountry: "Central Asia 🌿",
    originStory_zh: "大蒜的栽培历史悠久，常作为“爆香”的起点。它在热油中释放出浓郁香气，形成许多菜的底味。",
    originStory_en: "Garlic has long been cultivated and often starts a dish’s aroma. In hot oil, it releases powerful fragrance that forms a flavor base.",
    originStory_id: "Bawang putih sudah lama dibudidayakan dan sering jadi awal aroma masakan. Saat ditumis di minyak panas, aromanya kuat dan jadi dasar rasa.",
    originStory_hi: "लहसुन की खेती लंबे समय से होती आई है और यह कई व्यंजनों की खुशबू की शुरुआत होता है। गर्म तेल में इसका सुगंधित स्वाद बेस बनता है।",
    funFact_zh: "切开或捣碎大蒜后会更香，是因为化学反应产生了新的香味物质。",
    funFact_en: "Chopped garlic becomes more aromatic because enzymes create new flavor compounds.",
    funFact_id: "Bawang putih makin wangi setelah dicincang karena enzim membentuk senyawa rasa baru.",
    funFact_hi: "कटा/कूटा लहसुन अधिक खुशबूदार होता है क्योंकि एंज़ाइम नए फ्लेवर यौगिक बनाते हैं।"
  },
  "Garlic powder": {
    id: "garlic_powder",
    name_zh: "蒜粉",
    name_en: "Garlic powder",
    name_id: "Bubuk bawang putih",
    name_hi: "लहसुन पाउडर",
    originCountry: "Worldwide 🌍",
    originStory_zh: "把大蒜脱水研磨成粉能长期保存，也方便均匀调味。常用于腌料、炸物或快手料理。",
    originStory_en: "Garlic powder is dehydrated garlic ground fine for long storage and even seasoning. It’s common in rubs and quick dishes.",
    originStory_id: "Bubuk bawang putih adalah bawang putih kering yang dihaluskan agar awet dan mudah merata. Sering dipakai untuk bumbu tabur atau marinasi.",
    originStory_hi: "लहसुन पाउडर सूखे लहसुन को पीसकर बनाया जाता है ताकि लंबे समय तक रखा जा सके और मसाला समान रूप से मिले।",
    funFact_zh: "蒜粉更偏“香”，而新鲜蒜更偏“冲”，两者风味不完全一样。",
    funFact_en: "Garlic powder is more mellow and aromatic, while fresh garlic can be sharper.",
    funFact_id: "Bubuk bawang putih lebih lembut aromanya, sedangkan bawang putih segar bisa lebih tajam.",
    funFact_hi: "लहसुन पाउडर ज्यादा माइल्ड और एरोमैटिक होता है, जबकि ताज़ा लहसुन अधिक तीखा हो सकता है।"
  },
  Ghee: {
    id: "ghee",
    name_zh: "酥油",
    name_en: "Ghee",
    name_id: "Ghee",
    name_hi: "घी",
    originCountry: "South Asia 🇮🇳",
    originStory_zh: "酥油是澄清黄油，去除了水分和乳固形物，更耐高温。它在南亚料理中常用作主要烹饪油脂。",
    originStory_en: "Ghee is clarified butter with water and milk solids removed, making it stable at higher heat. It’s widely used in South Asian cooking.",
    originStory_id: "Ghee adalah mentega jernih tanpa air dan padatan susu, jadi lebih tahan panas. Umum dipakai di masakan Asia Selatan.",
    originStory_hi: "घी साफ़ किया हुआ मक्खन है जिसमें पानी और मिल्क सॉलिड्स हटाए जाते हैं, इसलिए यह ऊँची आँच पर स्थिर रहता है। दक्षिण एशियाई खाना पकाने में यह आम है।",
    funFact_zh: "酥油的烟点通常比普通黄油更高，更适合煎炒。",
    funFact_en: "Ghee typically has a higher smoke point than regular butter.",
    funFact_id: "Ghee biasanya punya titik asap lebih tinggi daripada mentega biasa.",
    funFact_hi: "घी का स्मोक पॉइंट आम मक्खन से अधिक होता है।"
  },
  Ginger: {
    id: "ginger",
    name_zh: "姜",
    name_en: "Ginger",
    name_id: "Jahe",
    name_hi: "अदरक",
    originCountry: "Southeast Asia 🌿",
    originStory_zh: "姜在亚洲多地是常见的去腥与提香食材。它的辛香能为汤、炒菜和腌料提供“底劲”。",
    originStory_en: "Ginger is common across Asian cuisines for aroma and balance. Its warmth adds depth to soups, stir-fries, and marinades.",
    originStory_id: "Jahe umum di banyak masakan Asia untuk aroma dan penyeimbang. Rasanya memberi kedalaman pada sup, tumisan, dan marinasi.",
    originStory_hi: "अदरक कई एशियाई रसोइयों में खुशबू और संतुलन के लिए इस्तेमाल होता है। इसकी गर्माहट सूप, स्टिर-फ्राय और मरीनेड में गहराई जोड़ती है।",
    funFact_zh: "姜的辛辣感来自姜辣素，加热后会变得更温和。",
    funFact_en: "Ginger’s bite comes from gingerols, which mellow as they cook.",
    funFact_id: "Rasa ‘nendang’ jahe berasal dari gingerol yang akan lebih lembut saat dimasak.",
    funFact_hi: "अदरक का तीखापन जिंजरोल्स से आता है जो पकने पर माइल्ड हो जाते हैं।"
  },
  "Green onion": {
    id: "green_onion",
    name_zh: "葱",
    name_en: "Green onion",
    name_id: "Daun bawang",
    name_hi: "हरा प्याज़",
    originCountry: "Asia 🌿",
    originStory_zh: "葱在很多菜里既能做香料也能做装饰。常在出锅前加入，保留清香与脆感。",
    originStory_en: "Green onions are used for both aroma and garnish. They’re often added at the end to keep fresh bite.",
    originStory_id: "Daun bawang dipakai untuk aroma dan hiasan. Sering ditambahkan di akhir agar tetap segar dan renyah.",
    originStory_hi: "हरा प्याज़ खुशबू और गार्निश दोनों के लिए उपयोग होता है। इसे अक्सर अंत में डालते हैं ताकि ताज़गी बनी रहे।",
    funFact_zh: "葱白和葱绿风味不同：葱白更辛香，葱绿更清新。",
    funFact_en: "White and green parts taste different: whites are sharper, greens are fresher.",
    funFact_id: "Bagian putih lebih tajam, bagian hijau lebih segar aromanya.",
    funFact_hi: "सफेद हिस्सा ज्यादा तीखा, हरा हिस्सा ज्यादा ताज़ा स्वाद देता है।"
  },
  "Green peas": {
    id: "green_peas",
    name_zh: "青豌豆",
    name_en: "Green peas",
    name_id: "Kacang polong",
    name_hi: "हरी मटर",
    originCountry: "Middle East 🌿",
    originStory_zh: "豌豆在欧亚多地有悠久的栽培史，既能做蔬菜也能做干豆类。它的甜味和颗粒感很适合炒饭和咖喱。",
    originStory_en: "Peas have long been cultivated across Eurasia as both fresh vegetable and dried legume. Their sweetness works well in rice and curries.",
    originStory_id: "Kacang polong sudah lama dibudidayakan di Eurasia. Rasanya manis dan cocok untuk nasi goreng maupun kari.",
    originStory_hi: "मटर की खेती यूरेशिया में लंबे समय से होती रही है। इसकी मिठास चावल और करी में अच्छी लगती है।",
    funFact_zh: "冷冻豌豆往往是在采摘后很快冷冻，因此甜味能被保留下来。",
    funFact_en: "Frozen peas are often frozen soon after harvest, helping preserve sweetness.",
    funFact_id: "Kacang polong beku biasanya cepat dibekukan setelah panen sehingga manisnya terjaga.",
    funFact_hi: "फ्रोजन मटर अक्सर कटाई के तुरंत बाद फ्रीज़ होती है, जिससे मिठास बनी रहती है।"
  },
  "Ground beef": {
    id: "ground_beef",
    name_zh: "牛肉末",
    name_en: "Ground beef",
    name_id: "Daging sapi cincang",
    name_hi: "कीमा",
    originCountry: "Worldwide 🌍",
    originStory_zh: "绞肉能更快入味、也更易做成肉饼或酱料。它在许多家庭菜里是高效的蛋白选择。",
    originStory_en: "Ground meat seasons quickly and forms patties or sauces easily. It’s a practical protein in many home kitchens.",
    originStory_id: "Daging cincang cepat menyerap bumbu dan mudah dibentuk jadi patty atau saus. Praktis untuk masak rumahan.",
    originStory_hi: "कीमा जल्दी मसाला पकड़ता है और पैटी/सॉस बनाना आसान होता है। यह घर में पकाने के लिए सुविधाजनक प्रोटीन है।",
    funFact_zh: "绞肉越细，受热越快，但也更容易过熟变干。",
    funFact_en: "Finer grind cooks faster but can dry out more easily if overcooked.",
    funFact_id: "Cincangan lebih halus matang lebih cepat, tapi bisa lebih mudah kering jika terlalu matang.",
    funFact_hi: "बारीक कीमा जल्दी पकता है, लेकिन ओवरकुक होने पर सूख भी सकता है।"
  },
  "Hard-boiled egg": {
    id: "hard_boiled_egg",
    name_zh: "水煮蛋",
    name_en: "Hard-boiled egg",
    name_id: "Telur rebus",
    name_hi: "उबला अंडा",
    originCountry: "Worldwide 🌍",
    originStory_zh: "水煮蛋简单耐放，常作为便当、沙拉或配菜。不同熟度能带来不同口感。",
    originStory_en: "Hard-boiled eggs are simple and portable, used in lunches, salads, and sides. Different timings create different textures.",
    originStory_id: "Telur rebus praktis dan mudah dibawa, cocok untuk bekal, salad, atau lauk. Waktu merebus memengaruhi tekstur.",
    originStory_hi: "उबले अंडे सरल और ले जाने में आसान होते हैं, सलाद/लंच/साइड में काम आते हैं। समय से टेक्सचर बदलता है।",
    funFact_zh: "把蛋放入冰水里能更容易剥壳，也能停止继续熟化。",
    funFact_en: "An ice bath makes peeling easier and stops carryover cooking.",
    funFact_id: "Merendam telur di air es membantu mengupas dan menghentikan proses matang lanjut.",
    funFact_hi: "आइस बाथ से छिलका आसानी से उतरता है और अंडा आगे पकना बंद कर देता है।"
  },
  Lettuce: {
    id: "lettuce",
    name_zh: "生菜",
    name_en: "Lettuce",
    name_id: "Selada",
    name_hi: "लेट्यूस",
    originCountry: "Mediterranean 🥬",
    originStory_zh: "生菜在地中海地区有悠久历史，后来成为全球常见的沙拉蔬菜。清脆口感也常用于汉堡夹层。",
    originStory_en: "Lettuce has Mediterranean roots and became a global salad staple. Its crunch also makes it a popular burger layer.",
    originStory_id: "Selada berakar di Mediterania dan kini populer sebagai sayuran salad. Teksturnya renyah, cocok juga untuk burger.",
    originStory_hi: "लेट्यूस की जड़ें भूमध्यसागरीय क्षेत्र में हैं और यह दुनिया भर में सलाद का स्टेपल बन गया। इसकी क्रंच बर्गर में भी अच्छा लगता है।",
    funFact_zh: "生菜含水量高，遇热容易塌软，所以多用于冷食或最后加入。",
    funFact_en: "Lettuce is high in water and wilts quickly with heat, so it’s often used cold or added last.",
    funFact_id: "Selada berair dan cepat layu saat panas, jadi biasanya dimakan mentah atau ditambahkan terakhir.",
    funFact_hi: "लेट्यूस में पानी ज्यादा होता है और यह गर्मी में जल्दी मुरझाता है, इसलिए इसे अक्सर ठंडा या अंत में डाला जाता है।"
  },
  "Lemon juice": {
    id: "lemon_juice",
    name_zh: "柠檬汁",
    name_en: "Lemon juice",
    name_id: "Jus lemon",
    name_hi: "नींबू रस",
    originCountry: "Mediterranean 🍋",
    originStory_zh: "柠檬的酸味常用于提亮味道、去腥或平衡油脂。少量就能让整体更清爽。",
    originStory_en: "Lemon juice brightens flavor, balances richness, and can reduce odors. A small squeeze can lift a whole dish.",
    originStory_id: "Jus lemon mencerahkan rasa, menyeimbangkan lemak, dan membantu mengurangi bau. Sedikit saja sudah terasa.",
    originStory_hi: "नींबू रस स्वाद को ब्राइट करता है, रिचनेस को बैलेंस करता है और गंध कम कर सकता है। थोड़ी सी मात्रा भी काफी होती है।",
    funFact_zh: "酸能抑制褐变，所以切好的水果滴点柠檬汁更不易变色。",
    funFact_en: "Acid can slow browning, which is why lemon helps cut fruit stay lighter.",
    funFact_id: "Asam dapat memperlambat pencokelatan, jadi lemon membantu buah potong tidak cepat berubah warna.",
    funFact_hi: "एसिड ब्राउनिंग को धीमा करता है, इसलिए नींबू कटे फल को हल्का बनाए रख सकता है।"
  },
  Lime: {
    id: "lime",
    name_zh: "青柠",
    name_en: "Lime",
    name_id: "Jeruk nipis",
    name_hi: "लाइम",
    originCountry: "Southeast Asia 🍋‍🟩",
    originStory_zh: "青柠在热带地区常见，酸香更清亮。它在东南亚料理里常作为点睛的酸味来源。",
    originStory_en: "Limes are common in tropical regions and taste bright and aromatic. They’re a key finishing acid in Southeast Asian cooking.",
    originStory_id: "Jeruk nipis umum di daerah tropis, rasanya segar dan wangi. Sering jadi penyeimbang asam di masakan Asia Tenggara.",
    originStory_hi: "लाइम उष्णकटिबंधीय क्षेत्रों में आम है और इसका स्वाद ब्राइट होता है। दक्षिण-पूर्व एशियाई पकवानों में यह अक्सर फिनिशिंग एसिड के रूप में आता है।",
    funFact_zh: "青柠皮里的精油非常香，擦一点皮屑能明显提香。",
    funFact_en: "Lime zest contains aromatic oils that can perfume a dish.",
    funFact_id: "Kulit jeruk nipis mengandung minyak aromatik yang wangi untuk mengangkat rasa.",
    funFact_hi: "लाइम के छिलके में सुगंधित तेल होते हैं जो डिश की खुशबू बढ़ा सकते हैं।"
  },
  "Lime juice": {
    id: "lime_juice",
    name_zh: "青柠汁",
    name_en: "Lime juice",
    name_id: "Jus jeruk nipis",
    name_hi: "लाइम रस",
    originCountry: "Tropics 🍋‍🟩",
    originStory_zh: "青柠汁常用于平衡辣味和油脂，让味道更轻盈。它在蘸酱和凉拌里尤其常见。",
    originStory_en: "Lime juice balances heat and richness and keeps flavors lively. It’s common in dips and fresh salads.",
    originStory_id: "Jus jeruk nipis menyeimbangkan pedas dan rasa ‘berat’, membuat rasa lebih segar. Sering dipakai untuk sambal dan salad.",
    originStory_hi: "लाइम रस तीखापन और रिचनेस को बैलेंस करता है और स्वाद को फ्रेश रखता है। डिप्स और सलाद में आम है।",
    funFact_zh: "酸会让蛋白质变性，所以柑橘汁能“腌熟”海鲜（如酸橘汁腌鱼）。",
    funFact_en: "Acid can denature proteins, which is why citrus can ‘cook’ seafood in ceviche-style dishes.",
    funFact_id: "Asam bisa mendenaturasi protein, sehingga jeruk bisa ‘mematangkan’ seafood ala ceviche.",
    funFact_hi: "एसिड प्रोटीन को डिनैचर कर सकता है, इसलिए साइट्रस जूस कुछ डिश में समुद्री भोजन को ‘कुक’ जैसा कर देता है।"
  },
  Milk: {
    id: "milk",
    name_zh: "牛奶",
    name_en: "Milk",
    name_id: "Susu",
    name_hi: "दूध",
    originCountry: "Worldwide 🥛",
    originStory_zh: "牛奶是许多饮食文化中的基础原料，可做饮品、酱汁、甜点与奶酪。不同加热方式会影响口感和香气。",
    originStory_en: "Milk is a foundational ingredient used in drinks, sauces, sweets, and cheese. Heating changes texture and aroma.",
    originStory_id: "Susu adalah bahan dasar untuk minuman, saus, dessert, dan keju. Pemanasan memengaruhi tekstur dan aroma.",
    originStory_hi: "दूध पेय, सॉस, मिठाई और चीज़ में इस्तेमाल होने वाली आधारभूत सामग्री है। गर्म करने से टेक्सचर और खुशबू बदलती है।",
    funFact_zh: "牛奶里的乳糖受热会参与褐变反应，带来焦糖样香气。",
    funFact_en: "Milk sugars can brown with heat, creating a subtle caramel-like aroma.",
    funFact_id: "Gula susu bisa mengalami browning saat dipanaskan dan memberi aroma mirip karamel.",
    funFact_hi: "दूध की शक्कर गर्मी में ब्राउन होकर हल्की कारमेल जैसी खुशबू दे सकती है।"
  },
  Mint: {
    id: "mint",
    name_zh: "薄荷",
    name_en: "Mint",
    name_id: "Mint",
    name_hi: "पुदीना",
    originCountry: "Mediterranean 🌿",
    originStory_zh: "薄荷的清凉感能让菜肴更清爽，常用于沙拉、饮品与酱料。它在热菜中多在最后点缀。",
    originStory_en: "Mint’s cooling aroma refreshes dishes and is common in salads, drinks, and sauces. In hot dishes it’s usually added at the end.",
    originStory_id: "Aroma mint memberi sensasi segar dan sering dipakai di salad, minuman, dan saus. Untuk masakan panas biasanya ditambahkan terakhir.",
    originStory_hi: "पुदीना डिश को ताज़गी देता है और सलाद, पेय व सॉस में आम है। गरम डिश में इसे अक्सर अंत में डाला जाता है।",
    funFact_zh: "薄荷的清凉并不是温度降低，而是刺激了“凉感”受体。",
    funFact_en: "Mint feels cool because menthol triggers ‘cool’ receptors, not because it lowers temperature.",
    funFact_id: "Mint terasa dingin karena mentol memicu reseptor ‘dingin’, bukan karena suhu benar-benar turun.",
    funFact_hi: "पुदीना ठंडा लगता है क्योंकि मेंथॉल ‘कूल’ रिसेप्टर्स को सक्रिय करता है, तापमान कम नहीं करता।"
  },
  Noodles: {
    id: "noodles",
    name_zh: "面条",
    name_en: "Noodles",
    name_id: "Mie",
    name_hi: "नूडल्स",
    originCountry: "China 🇨🇳",
    originStory_zh: "面条在东亚饮食中历史悠久，形态丰富。它既可作主食，也能作为汤面或炒面的基础。",
    originStory_en: "Noodles have a long history in East Asia with many shapes. They serve as staples in soups and stir-fries.",
    originStory_id: "Mie punya sejarah panjang di Asia Timur dengan banyak bentuk. Dipakai untuk sup maupun tumisan.",
    originStory_hi: "नूडल्स का पूर्वी एशिया में लंबा इतिहास है और कई आकार हैं। यह सूप और स्टिर-फ्राय दोनों में स्टेपल है।",
    funFact_zh: "煮面水里加一点盐能略微提升面条的筋道感。",
    funFact_en: "A little salt in noodle water can slightly improve texture and seasoning.",
    funFact_id: "Sedikit garam di air rebusan mie membantu rasa dan tekstur.",
    funFact_hi: "नूडल्स के पानी में थोड़ा नमक डालने से टेक्सचर और स्वाद बेहतर हो सकता है।"
  },
  Onion: {
    id: "onion",
    name_zh: "洋葱",
    name_en: "Onion",
    name_id: "Bawang bombai",
    name_hi: "प्याज़",
    originCountry: "Central Asia 🧅",
    originStory_zh: "洋葱是许多菜系的基础底味，生时辛辣，炒熟后会变得更甜。它常用于汤、酱和炒菜起香。",
    originStory_en: "Onions form a base in many cuisines: sharp when raw, sweet when cooked. They build flavor in soups, sauces, and stir-fries.",
    originStory_id: "Bawang bombai jadi dasar banyak masakan: tajam saat mentah, manis saat dimasak. Dipakai untuk sup, saus, dan tumisan.",
    originStory_hi: "प्याज़ कई रसोइयों का बेस है: कच्चा तीखा, पका मीठा। यह सूप, सॉस और स्टिर-फ्राय में फ्लेवर बनाता है।",
    funFact_zh: "切洋葱流泪是因为挥发性硫化物刺激了眼睛。",
    funFact_en: "Onions make you cry because volatile sulfur compounds irritate your eyes.",
    funFact_id: "Bawang membuat mata berair karena senyawa sulfur volatil mengiritasi mata.",
    funFact_hi: "प्याज़ काटने पर आँसू इसलिए आते हैं क्योंकि उड़ने वाले सल्फर यौगिक आँखों को चुभते हैं।"
  },
  "Onion powder": {
    id: "onion_powder",
    name_zh: "洋葱粉",
    name_en: "Onion powder",
    name_id: "Bubuk bawang",
    name_hi: "प्याज़ पाउडर",
    originCountry: "Worldwide 🌍",
    originStory_zh: "洋葱粉是脱水洋葱研磨而成，使用方便、味道均匀。适合做腌料、炸物或快手调味。",
    originStory_en: "Onion powder is dehydrated onion ground fine for convenient, even seasoning. It’s common in rubs and quick mixes.",
    originStory_id: "Bubuk bawang dibuat dari bawang kering yang dihaluskan agar praktis dan merata. Sering untuk bumbu tabur atau marinasi.",
    originStory_hi: "प्याज़ पाउडर सूखे प्याज़ को पीसकर बनाया जाता है ताकि जल्दी और समान मसाला मिले।",
    funFact_zh: "粉状调味更容易“过量”，建议少量多次加入。",
    funFact_en: "Powders can over-season quickly — add a little at a time.",
    funFact_id: "Bubuk bumbu mudah kebanyakan — tambahkan sedikit demi sedikit.",
    funFact_hi: "पाउडर मसाले जल्दी ज्यादा हो सकते हैं — थोड़ा-थोड़ा करके डालें।"
  },
  Paneer: {
    id: "paneer",
    name_zh: "帕尼尔奶酪",
    name_en: "Paneer",
    name_id: "Paneer",
    name_hi: "पनीर",
    originCountry: "India 🇮🇳",
    originStory_zh: "帕尼尔是一种不经熟成的鲜奶酪，常用于咖喱与炒菜。它受热不易融化，口感扎实。",
    originStory_en: "Paneer is a fresh, unaged cheese common in Indian cooking. It holds its shape when heated, making it ideal for curries.",
    originStory_id: "Paneer adalah keju segar tanpa pematangan yang umum di masakan India. Tidak mudah meleleh saat dipanaskan, cocok untuk kari.",
    originStory_hi: "पनीर एक ताज़ा, बिना एजिंग वाला चीज़ है जो भारतीय खाना पकाने में आम है। यह गर्म होने पर आसानी से नहीं पिघलता, इसलिए करी के लिए बढ़िया है।",
    funFact_zh: "帕尼尔通常用酸（柠檬汁/醋）凝固牛奶制作。",
    funFact_en: "Paneer is often made by curdling milk with acid like lemon juice or vinegar.",
    funFact_id: "Paneer biasanya dibuat dengan menggumpalkan susu menggunakan asam seperti lemon atau cuka.",
    funFact_hi: "पनीर अक्सर दूध को नींबू/सिरके जैसी एसिड से फाड़कर बनाया जाता है।"
  },
  Paprika: {
    id: "paprika",
    name_zh: "红椒粉",
    name_en: "Paprika",
    name_id: "Paprika",
    name_hi: "पपरिका",
    originCountry: "Hungary 🇭🇺",
    originStory_zh: "红椒粉由甜椒或辣椒干燥研磨而成，在欧洲多地流行。它带来颜色与温和的甜香。",
    originStory_en: "Paprika is ground dried peppers and is popular across Europe. It adds color and a mild sweet aroma.",
    originStory_id: "Paprika adalah bubuk dari cabai/paprika kering, populer di Eropa. Memberi warna dan aroma manis ringan.",
    originStory_hi: "पपरिका सूखी मिर्च/पेपर को पीसकर बनती है और यूरोप में लोकप्रिय है। यह रंग और हल्की मीठी खुशबू देती है।",
    funFact_zh: "烟熏红椒粉会有明显烟熏味，适合模拟烧烤香气。",
    funFact_en: "Smoked paprika can add a strong smoky note without a grill.",
    funFact_id: "Paprika asap memberi rasa smoky kuat tanpa perlu panggangan.",
    funFact_hi: "स्मोक्ड पपरिका ग्रिल के बिना भी स्मोकी स्वाद दे सकती है।"
  },
  "Peanut butter": {
    id: "peanut_butter",
    name_zh: "花生酱",
    name_en: "Peanut butter",
    name_id: "Selai kacang",
    name_hi: "मूंगफली मक्खन",
    originCountry: "United States 🇺🇸",
    originStory_zh: "花生酱在美国很普遍，后来也被许多菜系用来做酱汁。它带来坚果香与浓稠口感。",
    originStory_en: "Peanut butter is common in the U.S. and is also used in sauces in many cuisines. It adds nutty richness and thickness.",
    originStory_id: "Selai kacang populer di AS dan juga dipakai sebagai saus di banyak masakan. Memberi rasa kacang yang kaya dan tekstur kental.",
    originStory_hi: "पीनट बटर अमेरिका में आम है और कई रसोइयों में इसे सॉस के रूप में भी इस्तेमाल करते हैं। यह नटी रिचनेस और गाढ़ापन देता है।",
    funFact_zh: "花生酱和辣味很搭：脂肪能让辣度更柔和、香气更突出。",
    funFact_en: "Peanut butter pairs well with heat — fat smooths spice and carries aroma.",
    funFact_id: "Selai kacang cocok dengan pedas — lemaknya menyeimbangkan pedas dan membawa aroma.",
    funFact_hi: "पीनट बटर और तीखापन अच्छी जोड़ी हैं — फैट मसाले को स्मूथ करता है और खुशबू उठाता है।"
  },
  "Peanut sauce": {
    id: "peanut_sauce",
    name_zh: "花生酱汁",
    name_en: "Peanut sauce",
    name_id: "Bumbu kacang",
    name_hi: "पीनट सॉस",
    originCountry: "Indonesia 🇮🇩",
    originStory_zh: "花生酱汁在印尼等地常用于沙嗲和蘸酱。把烤花生磨成酱再调味，味道浓郁。",
    originStory_en: "Peanut sauce is common in Indonesia for satay and dipping. Roasted peanuts are ground and seasoned into a rich sauce.",
    originStory_id: "Bumbu kacang umum di Indonesia untuk sate dan cocolan. Kacang disangrai lalu dihaluskan dan dibumbui jadi saus kaya rasa.",
    originStory_hi: "पीनट सॉस इंडोनेशिया में साते और डिप के लिए आम है। भुनी मूंगफली को पीसकर मसाले मिलाकर रिच सॉस बनता है।",
    funFact_zh: "把花生先烤香再研磨，会让酱汁的坚果香更突出。",
    funFact_en: "Toasting peanuts before grinding boosts the nutty aroma.",
    funFact_id: "Menyangrai kacang sebelum diulek membuat aromanya lebih kuat.",
    funFact_hi: "पीसने से पहले मूंगफली को टोस्ट करने से नटी खुशबू बढ़ती है।"
  },
  Pickle: {
    id: "pickle",
    name_zh: "酸黄瓜",
    name_en: "Pickle",
    name_id: "Acar",
    name_hi: "अचार",
    originCountry: "Worldwide 🌍",
    originStory_zh: "腌制是古老的保存方法，不同地区用盐、醋或发酵形成各自风味。酸味能平衡油脂。",
    originStory_en: "Pickling is an ancient preservation method using salt, vinegar, or fermentation. Acidity balances rich foods.",
    originStory_id: "Acar adalah cara pengawetan kuno dengan garam, cuka, atau fermentasi. Rasa asam menyeimbangkan makanan berlemak.",
    originStory_hi: "अचार बनाना पुरानी संरक्षण विधि है—नमक, सिरका या फर्मेंटेशन से अलग स्वाद बनते हैं। खट्टापन रिच खाने को बैलेंस करता है।",
    funFact_zh: "发酵酸味来自乳酸菌，它们把糖转化成乳酸。",
    funFact_en: "Fermented pickles get tang from lactic acid bacteria turning sugars into acid.",
    funFact_id: "Acar fermentasi terasa asam karena bakteri asam laktat mengubah gula jadi asam.",
    funFact_hi: "फर्मेंटेड अचार की खटास लैक्टिक एसिड बैक्टीरिया से आती है जो शक्कर को एसिड में बदलते हैं।"
  },
  Pork: {
    id: "pork",
    name_zh: "猪肉",
    name_en: "Pork",
    name_id: "Daging babi",
    name_hi: "सूअर का मांस",
    originCountry: "Worldwide 🌍",
    originStory_zh: "猪肉在许多地区都是重要蛋白来源，可用煎、烤、炖、炒等多种方式烹饪。不同部位适合不同做法。",
    originStory_en: "Pork is an important protein in many cuisines and can be grilled, braised, fried, or stir-fried. Different cuts suit different methods.",
    originStory_id: "Daging babi penting di banyak masakan dan bisa dipanggang, disemur, digoreng, atau ditumis. Tiap bagian cocok untuk teknik berbeda.",
    originStory_hi: "कई रसोइयों में सूअर का मांस महत्वपूर्ण प्रोटीन है और इसे ग्रिल, ब्रेज़, फ्राई या स्टिर-फ्राय किया जाता है। अलग कट अलग तरीके के लिए बेहतर होते हैं।",
    funFact_zh: "五花肉之所以香，是因为肥瘦相间，加热后油脂能带出香气。",
    funFact_en: "Fatty cuts taste richer because rendered fat carries aroma and keeps meat juicy.",
    funFact_id: "Bagian berlemak terasa lebih kaya karena lemak yang meleleh membawa aroma dan membuat daging juicy.",
    funFact_hi: "फैटी कट्स ज्यादा रिच लगते हैं क्योंकि पिघला फैट खुशबू और जूसीपन दोनों देता है।"
  },
  "Pork ribs": {
    id: "pork_ribs",
    name_zh: "排骨",
    name_en: "Pork ribs",
    name_id: "Iga babi",
    name_hi: "पोर्क रिब्स",
    originCountry: "Worldwide 🌍",
    originStory_zh: "排骨常用于炖煮或烧烤，骨边肉的风味更浓。低温慢烹能让结缔组织变软。",
    originStory_en: "Ribs are popular for braising or BBQ, and meat near the bone is especially flavorful. Slow cooking tenderizes connective tissue.",
    originStory_id: "Iga sering dimasak semur atau BBQ, daging dekat tulang rasanya lebih kuat. Masak pelan membuat jaringan ikat jadi empuk.",
    originStory_hi: "रिब्स को अक्सर ब्रेज़ या BBQ किया जाता है और हड्डी के पास का मांस अधिक स्वादिष्ट होता है। धीमी पकाई से कनेक्टिव टिश्यू नरम होता है।",
    funFact_zh: "慢烤/慢炖能把胶原蛋白转成明胶，口感更软糯。",
    funFact_en: "Slow cooking converts collagen into gelatin for a tender, silky texture.",
    funFact_id: "Masak pelan mengubah kolagen menjadi gelatin sehingga teksturnya lembut.",
    funFact_hi: "धीमी पकाई कोलेजन को जेलैटिन में बदल देती है, जिससे टेक्सचर नरम और सिल्की होता है।"
  },
  Potato: {
    id: "potato",
    name_zh: "土豆",
    name_en: "Potato",
    name_id: "Kentang",
    name_hi: "आलू",
    originCountry: "Peru 🇵🇪",
    originStory_zh: "土豆原产于安第斯山区，后来传播到世界各地，成为重要主食作物。它能做出从绵到脆的多种口感。",
    originStory_en: "Potatoes originated in the Andes and spread worldwide as a staple crop. They can be creamy, fluffy, or crispy depending on cooking.",
    originStory_id: "Kentang berasal dari Andes dan menyebar jadi bahan pokok di banyak negara. Teksturnya bisa lembut sampai renyah tergantung cara masak.",
    originStory_hi: "आलू की उत्पत्ति एंडीज़ क्षेत्र में हुई और यह दुनिया भर में स्टेपल फसल बन गया। पकाने के तरीके से यह नरम या कुरकुरा बन सकता है।",
    funFact_zh: "不同土豆淀粉含量不同：高淀粉更适合炸和烤。",
    funFact_en: "Different potatoes have different starch levels; high-starch ones crisp better for fries.",
    funFact_id: "Kadar pati kentang berbeda-beda; yang tinggi pati lebih renyah untuk goreng.",
    funFact_hi: "अलग आलू में स्टार्च अलग होता है; हाई-स्टार्च आलू फ्राइज के लिए ज्यादा कुरकुरे बनते हैं।"
  },
  "Red lentils": {
    id: "red_lentils",
    name_zh: "红扁豆",
    name_en: "Red lentils",
    name_id: "Lentil merah",
    name_hi: "मसूर दाल",
    originCountry: "Middle East 🫘",
    originStory_zh: "扁豆在西亚地区有悠久的食用历史，易煮烂、适合做汤和达尔。它是重要植物蛋白来源。",
    originStory_en: "Lentils have long roots in the Middle East and cook quickly, ideal for soups and dals. They’re a major plant protein.",
    originStory_id: "Lentil sudah lama dikonsumsi di Timur Tengah dan cepat empuk, cocok untuk sup dan dal. Sumber protein nabati penting.",
    originStory_hi: "मसूर दाल की जड़ें मध्य पूर्व में पुरानी हैं और यह जल्दी गल जाती है, इसलिए सूप/दाल के लिए बढ़िया है। यह पौध-आधारित प्रोटीन का अच्छा स्रोत है।",
    funFact_zh: "红扁豆去皮后更容易煮化，所以常用来做浓稠口感。",
    funFact_en: "Red lentils break down easily, making them great for creamy textures without dairy.",
    funFact_id: "Lentil merah mudah hancur saat dimasak sehingga kuah jadi kental tanpa susu.",
    funFact_hi: "रेड लेंटिल्स आसानी से टूटकर गाढ़ापन देते हैं, बिना डेयरी के क्रीमी टेक्सचर बनता है।"
  },
  "Rice vermicelli": {
    id: "rice_vermicelli",
    name_zh: "米粉",
    name_en: "Rice vermicelli",
    name_id: "Bihun",
    name_hi: "चावल सेवई",
    originCountry: "China 🇨🇳",
    originStory_zh: "米粉以大米为主料，口感轻盈滑爽，常用于汤粉或炒粉。不同粗细适合不同做法。",
    originStory_en: "Rice vermicelli is made from rice and has a light, silky texture. It’s used in soups and stir-fries in many Asian cuisines.",
    originStory_id: "Bihun dibuat dari beras, teksturnya ringan dan lembut. Dipakai untuk sup maupun gorengan di banyak masakan Asia.",
    originStory_hi: "चावल सेवई/वर्मीसेली चावल से बनती है और टेक्सचर हल्का होता है। यह सूप और स्टिर-फ्राय में उपयोग होती है।",
    funFact_zh: "米粉泡软后再下锅更不易断，口感也更均匀。",
    funFact_en: "Soaking rice vermicelli before cooking helps prevent breakage and cooks it evenly.",
    funFact_id: "Merendam bihun sebelum dimasak membantu tidak mudah patah dan matang merata.",
    funFact_hi: "पकाने से पहले भिगोने से चावल सेवई कम टूटती है और समान रूप से पकती है।"
  },
  Salt: {
    id: "salt",
    name_zh: "盐",
    name_en: "Salt",
    name_id: "Garam",
    name_hi: "नमक",
    originCountry: "Everywhere 🧂",
    originStory_zh: "盐是最基础的调味品之一，也长期用于腌制保存。它不仅带来咸味，还能突出其他香味。",
    originStory_en: "Salt is one of the most basic seasonings and has long been used for preservation. It enhances other flavors, not just saltiness.",
    originStory_id: "Garam adalah bumbu paling dasar dan lama dipakai untuk mengawetkan. Garam juga mengangkat rasa lain, bukan cuma asin.",
    originStory_hi: "नमक सबसे बुनियादी मसालों में है और लंबे समय से संरक्षण के लिए उपयोग होता आया है। यह सिर्फ नमकीन नहीं, दूसरे स्वाद भी उभारता है।",
    funFact_zh: "少量盐能让甜味更明显，所以甜点里也常会加一撮盐。",
    funFact_en: "A pinch of salt can make sweetness taste brighter, which is why desserts often use it too.",
    funFact_id: "Sedikit garam bisa membuat rasa manis lebih ‘keluar’, jadi dessert pun sering pakai sejumput garam.",
    funFact_hi: "थोड़ा नमक मिठास को भी उभार सकता है, इसलिए मिठाइयों में भी चुटकी भर नमक डाला जाता है।"
  },
  Scallion: {
    id: "scallion",
    name_zh: "葱",
    name_en: "Scallion",
    name_id: "Daun bawang",
    name_hi: "हरा प्याज़",
    originCountry: "Asia 🌿",
    originStory_zh: "葱常用于增香、点缀与提鲜。不同切法会影响香气释放与口感。",
    originStory_en: "Scallions add aroma and freshness. How you slice them affects both texture and fragrance.",
    originStory_id: "Daun bawang menambah aroma dan segar. Cara memotong memengaruhi tekstur dan wangi.",
    originStory_hi: "हरा प्याज़ खुशबू और ताज़गी देता है। काटने का तरीका टेक्सचर और खुशबू दोनों बदलता है।",
    funFact_zh: "斜切能增加接触面积，香气更容易释放。",
    funFact_en: "Diagonal slices increase surface area, releasing more aroma.",
    funFact_id: "Potongan serong memperbesar permukaan sehingga aroma lebih keluar.",
    funFact_hi: "तिरछा काटने से सतह क्षेत्र बढ़ता है और खुशबू अधिक निकलती है।"
  },
  "Sea bass": {
    id: "sea_bass",
    name_zh: "海鲈鱼",
    name_en: "Sea bass",
    name_id: "Ikan seabass",
    name_hi: "सी बास मछली",
    originCountry: "Coasts 🌊",
    originStory_zh: "海鲈鱼肉质细嫩，适合清蒸、煎或做汤。温和的鱼味也很适合搭配姜葱去腥提香。",
    originStory_en: "Sea bass is tender and mild, good for steaming, pan-searing, or soups. Ginger and scallion are classic aromatic partners.",
    originStory_id: "Seabass lembut dan rasanya ringan, cocok dikukus, dipanggang pan, atau sup. Jahe dan daun bawang sering jadi pasangan aromanya.",
    originStory_hi: "सी बास का मांस नरम और स्वाद हल्का होता है, इसे स्टीम, पैन-सीयर या सूप में बनाया जाता है। अदरक और हरा प्याज़ इसकी खुशबू बढ़ाते हैं।",
    funFact_zh: "鱼肉过熟会变干，控制火候比多调味更关键。",
    funFact_en: "Fish dries out quickly when overcooked — timing matters more than extra seasoning.",
    funFact_id: "Ikan cepat kering kalau overcooked — timing lebih penting daripada bumbu berlebihan.",
    funFact_hi: "मछली ओवरकुक होने पर जल्दी सूख जाती है — समय का ध्यान मसालों से भी ज्यादा जरूरी है।"
  },
  Shallot: {
    id: "shallot",
    name_zh: "红葱头",
    name_en: "Shallot",
    name_id: "Bawang merah",
    name_hi: "शलोट",
    originCountry: "Asia 🌿",
    originStory_zh: "红葱头香气更甜更细腻，东南亚料理中非常常见。炸红葱酥是很多菜的“灵魂点缀”。",
    originStory_en: "Shallots are sweeter and more delicate than onions and are common in Southeast Asian cooking. Fried shallots are a beloved topping.",
    originStory_id: "Bawang merah lebih manis dan aromanya halus, sangat umum di masakan Asia Tenggara. Bawang goreng jadi taburan favorit.",
    originStory_hi: "शलोट प्याज़ से ज्यादा मीठा और डेलिकेट होता है और दक्षिण-पूर्व एशियाई पकवानों में आम है। फ्राइड शलोट्स लोकप्रिय टॉपिंग हैं।",
    funFact_zh: "红葱头炸过后会变得特别香，但也很容易从金黄变成焦黑。",
    funFact_en: "Fried shallots go from golden to burnt quickly — watch them closely.",
    funFact_id: "Bawang goreng cepat berubah dari keemasan ke gosong — harus diawasi.",
    funFact_hi: "फ्राइड शलोट्स बहुत जल्दी सुनहरे से जले हुए हो सकते हैं — ध्यान रखें।"
  },
  Spinach: {
    id: "spinach",
    name_zh: "菠菜",
    name_en: "Spinach",
    name_id: "Bayam",
    name_hi: "पालक",
    originCountry: "Persia 🇮🇷",
    originStory_zh: "菠菜被认为起源于古代波斯地区，后来传播到世界各地。它烹饪时间短，适合快炒或入汤。",
    originStory_en: "Spinach is thought to have originated in ancient Persia and spread widely. It cooks quickly and works well in stir-fries and soups.",
    originStory_id: "Bayam diyakini berasal dari Persia kuno dan menyebar luas. Cepat layu saat dimasak, cocok untuk tumis cepat atau sup.",
    originStory_hi: "पालक की उत्पत्ति प्राचीन फारस में मानी जाती है और यह व्यापक रूप से फैला। यह जल्दी पकता है, इसलिए स्टिर-फ्राय या सूप में अच्छा है।",
    funFact_zh: "菠菜含草酸，焯水能减少涩感并让颜色更绿。",
    funFact_en: "Blanching spinach can reduce oxalates and help keep a bright green color.",
    funFact_id: "Blansir bayam bisa mengurangi oksalat dan membuat warnanya tetap hijau cerah.",
    funFact_hi: "पालक को ब्लांच करने से ऑक्सलेट कम हो सकते हैं और रंग ज्यादा हरा बना रहता है।"
  },
  Thyme: {
    id: "thyme",
    name_zh: "百里香",
    name_en: "Thyme",
    name_id: "Thyme",
    name_hi: "थाइम",
    originCountry: "Mediterranean 🌿",
    originStory_zh: "百里香是地中海常见香草，耐煮耐烤，常用于烤肉、炖菜和酱汁增香。",
    originStory_en: "Thyme is a Mediterranean herb that holds up well to heat. It’s used in roasts, stews, and sauces.",
    originStory_id: "Thyme adalah herba Mediterania yang tahan panas. Dipakai untuk panggang, semur, dan saus.",
    originStory_hi: "थाइम भूमध्यसागरीय हर्ब है जो गर्मी में भी टिकता है। इसे रोस्ट, स्ट्यू और सॉस में उपयोग करते हैं।",
    funFact_zh: "百里香的香气在油脂中更容易释放，所以常配黄油或橄榄油使用。",
    funFact_en: "Thyme’s aroma dissolves into fat, so it blooms well in butter or oil.",
    funFact_id: "Aroma thyme larut dalam lemak, jadi wangi kalau dipanaskan dalam mentega atau minyak.",
    funFact_hi: "थाइम की खुशबू फैट में अच्छी तरह निकलती है, इसलिए बटर/तेल में ‘ब्लूम’ होती है।"
  },
  Tomato: {
    id: "tomato",
    name_zh: "西红柿",
    name_en: "Tomato",
    name_id: "Tomat",
    name_hi: "टमाटर",
    originCountry: "Mexico 🇲🇽",
    originStory_zh: "番茄原产于美洲，16世纪通过西班牙人传入欧洲，后来成为全球厨房的常客。酸甜的味道能为酱汁和炖菜提供基础。",
    originStory_en: "Tomatoes originated in the Americas and were brought to Europe by Spanish explorers in the 16th century. Their sweet acidity became a foundation for sauces and stews worldwide.",
    originStory_id: "Tomat berasal dari benua Amerika dan dibawa ke Eropa oleh penjelajah Spanyol pada abad ke-16. Rasa asam-manisnya jadi dasar banyak saus dan semur.",
    originStory_hi: "टमाटर की उत्पत्ति अमेरिका में हुई और 16वीं सदी में स्पेनिश खोजकर्ताओं द्वारा यूरोप लाया गया। इसकी मीठी-खट्टी प्रकृति सॉस और स्ट्यू का आधार बन गई।",
    funFact_zh: "番茄严格来说是水果，但美国最高法院在1893年把它在贸易上归类为蔬菜。",
    funFact_en: "Tomatoes are technically a fruit, but a U.S. Supreme Court ruling in 1893 classified them as vegetables for trade.",
    funFact_id: "Tomat secara botani adalah buah, tapi putusan Mahkamah Agung AS tahun 1893 menggolongkannya sebagai sayur untuk perdagangan.",
    funFact_hi: "टमाटर तकनीकी रूप से फल है, लेकिन 1893 में अमेरिकी सुप्रीम कोर्ट ने व्यापार के लिए इसे सब्ज़ी वर्ग में रखा।"
  },
  Water: {
    id: "water",
    name_zh: "水",
    name_en: "Water",
    name_id: "Air",
    name_hi: "पानी",
    originCountry: "Everywhere 💧",
    originStory_zh: "水是烹饪中最重要的“隐形食材”：煮、炖、蒸、和面都离不开它。水量与温度会直接影响口感。",
    originStory_en: "Water is the most important ‘invisible ingredient’ in cooking — boiling, steaming, braising, and dough all rely on it. Amount and temperature shape texture.",
    originStory_id: "Air adalah ‘bahan tak terlihat’ terpenting dalam memasak. Takaran dan suhu sangat memengaruhi tekstur hasil akhir.",
    originStory_hi: "पानी पकाने का सबसे महत्वपूर्ण ‘इनविज़िबल इंग्रीडिएंट’ है — उबालना, स्टीम, स्ट्यू और आटा सब इसी पर निर्भर हैं। मात्रा और तापमान टेक्सचर तय करते हैं।",
    funFact_zh: "海拔越高，水的沸点越低，所以高原地区需要更久才能煮熟食物。",
    funFact_en: "At higher altitude, water boils at a lower temperature, so cooking can take longer.",
    funFact_id: "Di tempat tinggi, air mendidih pada suhu lebih rendah sehingga memasak bisa lebih lama.",
    funFact_hi: "ऊँचाई बढ़ने पर पानी कम तापमान पर उबलता है, इसलिए खाना पकाने में अधिक समय लग सकता है।"
  }
};

function supplementalMeta(
  key: string,
  id: string,
  names: { zh: string; id: string; hi: string },
  originCountry: string,
  story: string,
  funFact: string
): IngredientMeta {
  return {
    id,
    name_zh: names.zh,
    name_en: key,
    name_id: names.id,
    name_hi: names.hi,
    originCountry,
    originStory_zh: `${names.zh}在多地厨房中都有重要角色，常用来为菜肴增加香气、口感或层次。`,
    originStory_en: story,
    originStory_id: `${names.id} punya peran penting di banyak dapur dunia, membantu memberi aroma, tekstur, atau rasa yang lebih berlapis.`,
    originStory_hi: `${names.hi} कई रसोइयों में अहम भूमिका निभाता है और पकवान में खुशबू, बनावट या स्वाद की परत जोड़ता है।`,
    funFact_zh: "不同的处理方式会明显改变它的香气和口感。",
    funFact_en: funFact,
    funFact_id: "Cara mengolahnya bisa sangat mengubah aroma dan teksturnya.",
    funFact_hi: "इसे संभालने या पकाने का तरीका इसकी खुशबू और बनावट को काफी बदल सकता है।"
  };
}

const SUPPLEMENTAL_INGREDIENTS: Record<string, IngredientMeta> = {
  Clams: supplementalMeta("Clams", "clams", { zh: "蛤蜊", id: "Kerang", hi: "क्लैम" }, "Coastal waters 🌊", "Clams have been gathered along coastlines for thousands of years and bring clean ocean sweetness to soups and stews.", "Clams open when heated because steam builds inside the shell."),
  "Pork gelatin": supplementalMeta("Pork gelatin", "pork_gelatin", { zh: "猪皮冻", id: "Gelatin babi", hi: "पोर्क जिलेटिन" }, "China 🇨🇳", "Gelatin made from pork skin or bones is used in soup dumplings and buns because it melts into broth during cooking.", "Cold gelatin turns into liquid soup as the bun heats."),
  "Shrimp crackers": supplementalMeta("Shrimp crackers", "shrimp_crackers", { zh: "虾片", id: "Kerupuk udang", hi: "झींगा क्रैकर" }, "Southeast Asia 🌴", "Shrimp crackers are common across Southeast Asia, especially Indonesia, where they add crunch beside rice dishes.", "They puff dramatically because trapped moisture turns to steam in hot oil."),
  "Shrimp paste": supplementalMeta("Shrimp paste", "shrimp_paste", { zh: "虾酱", id: "Terasi", hi: "झींगा पेस्ट" }, "Southeast Asia 🌴", "Fermented shrimp paste gives Southeast Asian dishes deep savory aroma and is often toasted before use.", "A tiny amount can season an entire wok because fermentation concentrates umami."),
  Tofu: supplementalMeta("Tofu", "tofu", { zh: "豆腐", id: "Tahu", hi: "टोफू" }, "China 🇨🇳", "Tofu originated in China and spread across Asia as a versatile soybean protein.", "Fresh tofu is mostly water, so gentle handling keeps the curds intact."),
  Celery: supplementalMeta("Celery", "celery", { zh: "芹菜", id: "Seledri", hi: "सेलेरी" }, "Mediterranean 🌿", "Celery was cultivated around the Mediterranean and became a classic aromatic base for soups and stews.", "Celery leaves are edible and often more aromatic than the stalks."),
  "Fried shallots": supplementalMeta("Fried shallots", "fried_shallots", { zh: "炸红葱酥", id: "Bawang goreng", hi: "तला शलोट" }, "Southeast Asia 🌴", "Fried shallots are a beloved Southeast Asian garnish that adds sweetness, aroma, and crunch.", "They keep crispest when drained well and salted after frying."),
  Galangal: supplementalMeta("Galangal", "galangal", { zh: "南姜", id: "Lengkuas", hi: "गलगल" }, "Southeast Asia 🌴", "Galangal is a rhizome used in Indonesian and Thai cooking for a peppery, pine-like aroma.", "It looks like ginger but tastes sharper and more citrusy."),
  Lemongrass: supplementalMeta("Lemongrass", "lemongrass", { zh: "香茅", id: "Serai", hi: "लेमनग्रास" }, "Southeast Asia 🌴", "Lemongrass is used across Southeast Asia to perfume soups, curries, and grilled foods.", "Bruising the stalk before cooking releases more fragrant oils."),
  "Long beans": supplementalMeta("Long beans", "long_beans", { zh: "长豆角", id: "Kacang panjang", hi: "लंबी फलियाँ" }, "South and Southeast Asia 🌿", "Long beans are common in tropical Asian cooking and stay pleasantly crisp in quick stir-fries.", "They are related to cowpeas and can grow much longer than green beans."),
  Flour: supplementalMeta("Flour", "flour", { zh: "面粉", id: "Tepung", hi: "आटा" }, "Worldwide 🌍", "Flour is ground grain and forms the base of breads, pastries, noodles, and sauces around the world.", "Protein level affects chew: higher protein usually means more gluten structure."),
  Yeast: supplementalMeta("Yeast", "yeast", { zh: "酵母", id: "Ragi", hi: "यीस्ट" }, "Worldwide 🌍", "Yeast is a living leavener that ferments sugars and helps dough rise.", "Yeast makes carbon dioxide and flavorful fermentation byproducts."),
  "Bay leaf": supplementalMeta("Bay leaf", "bay_leaf", { zh: "月桂叶", id: "Daun salam", hi: "तेज पत्ता" }, "Mediterranean 🌿", "Bay leaves are aromatic leaves used to slowly season soups, sauces, and braises.", "Whole bay leaves are usually removed before serving because they stay stiff."),
  "BBQ sauce": supplementalMeta("BBQ sauce", "bbq_sauce", { zh: "烧烤酱", id: "Saus BBQ", hi: "बारबेक्यू सॉस" }, "United States 🇺🇸", "BBQ sauce reflects American regional barbecue traditions, balancing smoke, sweetness, tang, and spice.", "Sugary sauces caramelize quickly, so they are often added near the end of cooking."),
  "Black pepper": supplementalMeta("Black pepper", "black_pepper", { zh: "黑胡椒", id: "Lada hitam", hi: "काली मिर्च" }, "India 🇮🇳", "Black pepper is native to India’s Malabar Coast and became one of history’s most traded spices.", "Freshly cracked pepper tastes brighter because volatile aromas fade after grinding."),
  "Brown sugar": supplementalMeta("Brown sugar", "brown_sugar", { zh: "红糖", id: "Gula merah", hi: "ब्राउन शुगर" }, "Worldwide 🌍", "Brown sugar contains molasses, which adds moisture and caramel depth to sauces and desserts.", "It can clump because molasses holds onto moisture."),
  Cinnamon: supplementalMeta("Cinnamon", "cinnamon", { zh: "肉桂", id: "Kayu manis", hi: "दालचीनी" }, "Sri Lanka 🇱🇰", "Cinnamon comes from tree bark and has long been prized in sweet and savory cooking.", "Cinnamon sticks slowly infuse liquids without making them cloudy."),
  "Coriander seeds": supplementalMeta("Coriander seeds", "coriander_seeds", { zh: "芫荽籽", id: "Biji ketumbar", hi: "धनिया बीज" }, "Mediterranean and Asia 🌿", "Coriander seeds are the dried fruit of cilantro and bring citrusy warmth to spice blends.", "Toasting seeds before grinding makes them taste nuttier."),
  Cream: supplementalMeta("Cream", "cream", { zh: "奶油", id: "Krim", hi: "क्रीम" }, "Worldwide 🌍", "Cream is the rich fat layer from milk and adds body to sauces, soups, and desserts.", "Higher fat cream is less likely to split when gently heated."),
  Cumin: supplementalMeta("Cumin", "cumin", { zh: "孜然", id: "Jinten", hi: "जीरा" }, "Eastern Mediterranean 🌿", "Cumin has traveled through Middle Eastern, Indian, Chinese, and Latin American cuisines for centuries.", "Blooming cumin in hot oil releases its earthy aroma."),
  "Dark soy sauce": supplementalMeta("Dark soy sauce", "dark_soy_sauce", { zh: "老抽", id: "Kecap asin gelap", hi: "डार्क सोया सॉस" }, "China 🇨🇳", "Dark soy sauce is thicker and darker than light soy sauce and is used mostly for color and gentle sweetness.", "A little dark soy sauce can make noodles look deeply glossy."),
  "Garam masala": supplementalMeta("Garam masala", "garam_masala", { zh: "印度综合香料", id: "Garam masala", hi: "गरम मसाला" }, "India 🇮🇳", "Garam masala is an Indian spice blend often added near the end of cooking for fragrance.", "Every household blend can taste different depending on roasted spices."),
  "Heavy cream": supplementalMeta("Heavy cream", "heavy_cream", { zh: "重奶油", id: "Krim kental", hi: "हैवी क्रीम" }, "Worldwide 🌍", "Heavy cream has a high fat content that gives sauces and desserts a luxurious texture.", "It can be whipped because fat globules trap air."),
  "Kecap manis": supplementalMeta("Kecap manis", "kecap_manis", { zh: "印尼甜酱油", id: "Kecap manis", hi: "केचप मनिस" }, "Indonesia 🇮🇩", "Kecap manis is Indonesia’s thick sweet soy sauce and is essential to nasi goreng.", "Its syrupy texture comes from palm sugar."),
  Ketchup: supplementalMeta("Ketchup", "ketchup", { zh: "番茄酱", id: "Saus tomat", hi: "केचप" }, "United States 🇺🇸", "Modern tomato ketchup became popular in the United States as a sweet-tangy condiment.", "Ketchup’s acidity helps cut through rich fried or grilled foods."),
  Mustard: supplementalMeta("Mustard", "mustard", { zh: "芥末酱", id: "Mustard", hi: "मस्टर्ड" }, "Europe and Asia 🌿", "Mustard seeds have been used for pungent sauces and seasonings across Europe and Asia.", "Mustard heat activates when ground seeds meet liquid."),
  Nutmeg: supplementalMeta("Nutmeg", "nutmeg", { zh: "肉豆蔻", id: "Pala", hi: "जायफल" }, "Indonesia 🇮🇩", "Nutmeg is native to Indonesia’s Banda Islands and became a treasured spice in global trade.", "A small pinch can make dairy sauces taste warmer and rounder."),
  Oil: supplementalMeta("Oil", "oil", { zh: "食用油", id: "Minyak", hi: "तेल" }, "Worldwide 🌍", "Cooking oil transfers heat, carries aroma, and helps browning in nearly every cuisine.", "Different oils have different smoke points, which changes how they behave in a hot pan."),
  Saffron: supplementalMeta("Saffron", "saffron", { zh: "藏红花", id: "Safron", hi: "केसर" }, "Iran 🇮🇷", "Saffron is made from crocus flower stigmas and is prized for color, aroma, and rarity.", "It takes thousands of flowers to produce a small amount of saffron."),
  Sesame: supplementalMeta("Sesame", "sesame", { zh: "芝麻", id: "Wijen", hi: "तिल" }, "Africa and Asia 🌍", "Sesame seeds are one of the oldest oilseed crops and add nutty flavor to many cuisines.", "Toasting sesame seeds makes their aroma much stronger."),
  "Sesame oil": supplementalMeta("Sesame oil", "sesame_oil", { zh: "芝麻油", id: "Minyak wijen", hi: "तिल का तेल" }, "East Asia 🌏", "Toasted sesame oil is used as a finishing aroma in many East Asian dishes.", "Because it is aromatic, a few drops at the end are often enough."),
  "Soy sauce": supplementalMeta("Soy sauce", "soy_sauce", { zh: "酱油", id: "Kecap asin", hi: "सोया सॉस" }, "China 🇨🇳", "Soy sauce is a fermented soybean seasoning that spread widely across East and Southeast Asia.", "Fermentation creates savory glutamates that make food taste deeper."),
  Sugar: supplementalMeta("Sugar", "sugar", { zh: "糖", id: "Gula", hi: "चीनी" }, "South and Southeast Asia 🌏", "Sugarcane was cultivated in Asia before spreading through global trade.", "Sugar balances acidity and helps browning through caramelization."),
  Turmeric: supplementalMeta("Turmeric", "turmeric", { zh: "姜黄", id: "Kunyit", hi: "हल्दी" }, "South Asia 🇮🇳", "Turmeric is a golden rhizome central to South Asian and Southeast Asian cooking.", "Its color comes from curcumin, which stains easily."),
  "Vegetable oil": supplementalMeta("Vegetable oil", "vegetable_oil", { zh: "植物油", id: "Minyak sayur", hi: "वनस्पति तेल" }, "Worldwide 🌍", "Vegetable oils are neutral cooking fats used for frying, sauteing, and baking.", "Neutral oil lets spices and aromatics stay in the spotlight."),
  Yogurt: supplementalMeta("Yogurt", "yogurt", { zh: "酸奶", id: "Yogurt", hi: "दही" }, "Central and South Asia 🌏", "Yogurt is fermented milk used for marinades, sauces, drinks, and cooling sides.", "Its lactic acid can help tenderize meat in marinades.")
};

export function getIngredientMeta(name: string) {
  return INGREDIENTS[name] ?? SUPPLEMENTAL_INGREDIENTS[name] ?? null;
}

export function getIngredientName(meta: IngredientMeta, language: LanguageCode) {
  if (language === "zh") return meta.name_zh;
  if (language === "id") return meta.name_id || meta.name_en;
  if (language === "hi") return meta.name_hi || meta.name_en;
  return meta.name_en;
}

export function getIngredientOriginStory(meta: IngredientMeta, language: LanguageCode) {
  if (language === "zh") return meta.originStory_zh;
  if (language === "id") return meta.originStory_id || meta.originStory_en;
  if (language === "hi") return meta.originStory_hi || meta.originStory_en;
  return meta.originStory_en;
}

export function getIngredientFunFact(meta: IngredientMeta, language: LanguageCode) {
  if (language === "zh") return meta.funFact_zh;
  if (language === "id") return meta.funFact_id || meta.funFact_en;
  if (language === "hi") return meta.funFact_hi || meta.funFact_en;
  return meta.funFact_en;
}

